# Generated by Django 3.2.5 on 2021-09-04 02:51

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('entidadID', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEntidad', models.CharField(help_text='Nombre Entidad Financiadora Convocatoria', max_length=200)),
                ('paginaWeb', models.URLField(help_text='Página Web de la Entidad', null=True)),
                ('pais', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('convocatoriaID', models.AutoField(primary_key=True, serialize=False)),
                ('tituloConvocatoria', models.CharField(help_text='Título de la Convocatoria', max_length=500)),
                ('descripcion', models.TextField(help_text='Resumen Convocatoria', max_length=2000)),
                ('fechaPublicacion', models.DateField(help_text='Fecha Publicación Convocatoria', null=True)),
                ('fechaLimitePostulacion', models.DateField(help_text='Fecha Límite Postulación', null=True)),
                ('paginaWebAplicacion', models.URLField(help_text='Página Web para aplicaciones', max_length=500, null=True)),
                ('vigencia', models.BooleanField(choices=[('False', 'No'), ('True', 'Sí')], default=True, editable=False, help_text='¿Se encuentra activa la convocatoria?')),
                ('entidadID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='convocatorias.entidad', verbose_name='Entidad Otorgante')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('contactoID', models.AutoField(primary_key=True, serialize=False)),
                ('cargoContacto', models.CharField(help_text='Cargo Contacto', max_length=200, null=True)),
                ('nombreContacto', models.CharField(help_text='Nombre Contacto', max_length=200)),
                ('correoContacto', models.EmailField(help_text='Correo Electrónico Contacto', max_length=254)),
                ('telefonoContacto', models.CharField(help_text='Teléfono de Contacto', max_length=200, null=True)),
                ('telefonoContactoAux', models.CharField(help_text='Teléfono de Contacto Auxiliar', max_length=200, null=True)),
                ('entidadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatorias.entidad')),
            ],
            options={
                'verbose_name_plural': 'Contactos Oficiales',
            },
        ),
        migrations.CreateModel(
            name='Caracterizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoFinanciacion', models.CharField(help_text='¿Qué tipo de financiación aplica para la convocatoria?', max_length=500)),
                ('montoBeneficio', models.CharField(help_text='¿Qué monto tiene la convocatoria?', max_length=500)),
                ('descripcionBeneficio', models.CharField(help_text='Descripción Beneficio Otorgado', max_length=2000, null=True)),
                ('periodica', models.CharField(blank=True, choices=[('no', 'No'), ('si', 'Sí')], default='n', help_text='¿Esta convocatoria es periódica?', max_length=2)),
                ('periodicidad', models.CharField(blank=True, choices=[('trimestral', 'trimestral'), ('anual', 'anual'), ('bianual', 'bianual'), ('na', 'no aplica')], default='na', help_text='¿qué periodicidad maneja esta convocatoria?', max_length=30)),
                ('ambito', models.CharField(blank=True, choices=[('local', 'local'), ('departamental', 'departamental'), ('nacional', 'nacional'), ('internacional', 'internacional'), ('na', 'no aplica')], default='na', help_text='¿cuál es el ámbito de la convocatoria?', max_length=30)),
                ('areasConvocatoria', models.CharField(blank=True, choices=[('ciencias_naturales', 'Ciencias Naturales'), ('ingenieria_tecnologia', 'Ingeniería y Tecnología'), ('ciencias_salud', 'Ciencias Médicas y de Salud'), ('ciencias_agricolas', 'Ciencias Agrícolas'), ('ciencias_sociales', 'Ciencias Sociales'), ('humanidades', 'Humanidades'), ('multidisciplinarias', 'Multidisciplinarias')], default='na', help_text='¿áreas de la convocatoria?', max_length=30)),
                ('convocatoriaID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='convocatorias.convocatoria')),
            ],
        ),
    ]
