# Generated by Django 3.2.5 on 2021-09-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefonoContactoAux',
            field=models.CharField(blank=True, help_text='Teléfono de Contacto Auxiliar', max_length=200, null=True),
        ),
    ]
