# Generated by Django 3.2.5 on 2021-09-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caracterizacion',
            old_name='OCDEareas',
            new_name='areasOCDE',
        ),
    ]
