# Generated by Django 3.2.5 on 2021-08-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='paginaWeb',
            field=models.URLField(help_text='Página Web de la Entidad', null=True),
        ),
    ]
