# Generated by Django 3.2.5 on 2021-09-21 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_rename_ocdeareas_caracterizacion_areasocde'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='caracterizacionID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='convocatorias.caracterizacion'),
        ),
        migrations.AlterField(
            model_name='caracterizacion',
            name='convocatoriaID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='convocatorias.convocatoria'),
        ),
    ]
