# Generated by Django 3.2.5 on 2021-08-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_entidad_paginaweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreContacto', models.CharField(help_text='Nombre Contacto', max_length=200)),
                ('correoContacto', models.EmailField(help_text='Correo Electrónico Contacto', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Contactos Oficiales',
            },
        ),
    ]
