# Generated by Django 3.2.5 on 2021-09-04 03:23

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('convocatorias', '0002_alter_contacto_telefonocontactoaux'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
