# Generated by Django 3.2.5 on 2021-09-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_convocatoria_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convocatoria',
            options={'verbose_name_plural': 'Registro de Convocatorias'},
        ),
        migrations.AlterModelOptions(
            name='entidad',
            options={'verbose_name_plural': 'Directorio de Entidades'},
        ),
        migrations.AddField(
            model_name='entidad',
            name='logoEntidad',
            field=models.ImageField(null=True, upload_to='entidad_logos'),
        ),
    ]
