# Generated by Django 3.2.5 on 2021-08-10 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='entidadID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='convocatorias.entidad'),
        ),
    ]
