# Generated by Django 3.2.5 on 2021-08-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0004_contacto_entidadid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='cargoContacto',
            field=models.CharField(help_text='Cargo Contacto', max_length=200, null=True),
        ),
    ]
