# Generated by Django 3.2.5 on 2021-09-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0006_auto_20210921_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='icono',
            name='colorIcono',
            field=models.CharField(help_text='Ingrese Color', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='icono',
            name='iconoTematico',
            field=models.CharField(help_text='Ingrese Código de Ícono', max_length=30, null=True),
        ),
    ]
