# Generated by Django 3.2.5 on 2021-09-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0007_auto_20210921_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icono',
            name='iconoTem',
        ),
    ]
