# Generated by Django 3.2.5 on 2021-08-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0007_alter_convocatoria_entidadid'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracterizacion',
            name='descripcionBeneficio',
            field=models.CharField(help_text='Descripción Beneficio Otorgado', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='caracterizacion',
            name='areasConvocatoria',
            field=models.CharField(blank=True, choices=[('ciencias_naturales', 'Ciencias Naturales'), ('ingenieria_tecnologia', 'Ingeniería y Tecnología'), ('ciencias_salud', 'Ciencias Médicas y de Salud'), ('ciencias_agricolas', 'Ciencias Agrícolas'), ('ciencias_sociales', 'Ciencias Sociales'), ('humanidades', 'Humanidades'), ('multidisciplinarias', 'Multidisciplinarias')], default='na', help_text='¿áreas de la convocatoria?', max_length=30),
        ),
    ]
