# Generated by Django 3.2.5 on 2021-08-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0008_auto_20210828_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='fechaLimitePostulacion',
            field=models.DateField(help_text='Fecha Límite Postulación', null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='paginaWebAplicacion',
            field=models.URLField(help_text='Página Web para aplicaciones', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='vigencia',
            field=models.BooleanField(choices=[('False', 'No'), ('True', 'Sí')], default=True, help_text='¿Se encuentra activa la convocatoria?'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='fechaPublicacion',
            field=models.DateField(help_text='Fecha Publicación Convocatoria', null=True),
        ),
    ]
