# Generated by Django 3.2.5 on 2021-09-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0008_remove_icono_iconotem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('componenteID', models.AutoField(primary_key=True, serialize=False)),
                ('componente', models.CharField(max_length=255, verbose_name='Área')),
            ],
            options={
                'verbose_name_plural': 'Componentes Convocatoria',
            },
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='Componentes',
            field=models.ManyToManyField(related_name='componentes', to='convocatorias.Componente', verbose_name='Componentes Convocatoria'),
        ),
    ]
