# Generated by Django 3.2.5 on 2021-09-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0009_auto_20210921_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elegibilidad',
            fields=[
                ('elegibilidadID', models.AutoField(primary_key=True, serialize=False)),
                ('elegibilidad', models.CharField(max_length=255, verbose_name='Área')),
            ],
            options={
                'verbose_name_plural': 'Elegibilidad Convocatoria',
            },
        ),
    ]
