# Generated by Django 3.2.5 on 2021-08-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0009_auto_20210829_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='vigencia',
            field=models.BooleanField(choices=[('False', 'No'), ('True', 'Sí')], default=True, editable=False, help_text='¿Se encuentra activa la convocatoria?'),
        ),
    ]
