# Generated by Django 3.2.5 on 2021-08-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0010_alter_convocatoria_vigencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convocatoria',
            options={},
        ),
    ]
