# Generated by Django 3.2.5 on 2021-09-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0011_convocatoria_elegibilidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elegibilidad',
            old_name='elegibilidad',
            new_name='grupo',
        ),
        migrations.RenameField(
            model_name='elegibilidad',
            old_name='elegibilidadID',
            new_name='grupoID',
        ),
        migrations.RemoveField(
            model_name='convocatoria',
            name='Elegibilidad',
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='elegibilidad',
            field=models.ManyToManyField(related_name='elegibilidad', to='convocatorias.Elegibilidad', verbose_name='Elegibilidad Convocatoria'),
        ),
    ]
