# Generated by Django 3.2.5 on 2021-09-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0012_auto_20210921_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='elegibilidad',
            field=models.ManyToManyField(related_name='elegibilidades', to='convocatorias.Elegibilidad', verbose_name='Elegibilidad Convocatoria'),
        ),
    ]
