# Generated by Django 3.2.5 on 2021-09-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0014_alter_convocatoria_elegibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='imageRedes',
            field=models.ImageField(null=True, upload_to='convocatorias_img_preview'),
        ),
    ]
