# Generated by Django 3.2.5 on 2021-09-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0015_convocatoria_imageredes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='imageRedes',
            field=models.ImageField(blank=True, null=True, upload_to='convocatorias_img_preview'),
        ),
    ]
